### ISSUE TITLE
Close Tab On Middle Click

### ISSUE THREAD

**Issue by tatarize** [EmbroidePy/EmbroidePy#13]
I often close tabs on a middle click, and can't do it with embroidepy.

Psst @Metallicow given your expertise in wxPython (Embroidermodder/Embroidermodder#27 your effect there knocked my sock off, while I was checking for UI elements to crib) is this something easy I missed in the implementation of notebook?

**Comment by tatarize** [comment]
You're more of an expert than I. I just hooked a bunch of stuff into `pyembroidery` which does the loading and saving akin to `libembroidery` with predefined post-processing that fixes bad command ordering and most of the bugs in libembroidery and fed them into a notebook as of panels for a sort of multiview thing then did the zooming and scaling. It's already generally good enough for most basic uses. But look as I did, that notebook interface had no method to detect middle click on tabs. So there's a pretty absurd menubar item for: `window`, `close tab`.

Basically everything else looked like it could be spruced up with some elbow grease adding in a few more dialogs as such, but I couldn't find anything to make those tabs operate more like the ones I'm used to. So if (in windows, the documentation suggested it might not work in other OSes) you drag and drop a directory of embroidery into the program, they all load up nicely. But, I'm stuck using a menu over and over again to shut down the tabs. Chrome has some nice enough tabs.  But, basically anything with tabs you can shut down with a middle click or an X on them or something. The default notebook doesn't seem to have that ability or an ability to get that ability.

**Comment by Metallicow** [comment]
@tatarize Ok. it looks like you are using wx.Notebook.
I didn't figure out how to grab enough info to do this with a basic notebook. I recall folks try and do this and get caught with the same issue. On the other hand, now that there is access to [wx.BookCtrlBase)](https://wxpython.org/Phoenix/docs/html/wx.BookCtrlBase.html#wx.BookCtrlBase) you can roll your own implementation if you want custom functionality. I've had the idea of rolling my own with my [ShapedBitmapButton](https://github.com/Metallicow/MCOW) widget and animation mods to do something like sublime text's slinky chrome tabs does. If you don't care much for doing a custom widget, your second bet would be AuiNotebook. It has middle click close as default. See attached sample. But with aui you need to know that it can be buggy, so if you go that route, then [wx.lib.agw.aui](https://wxpython.org/Phoenix/docs/html/wx.lib.agw.aui.html#module-wx.lib.agw.aui) is better depending on what you need. The original aui guy disappeared long ago and some stuff never got fixed, thus the port to pure python Andrea did. Since then agw aui has become quite a bit more stable with patches from us wxPy users, so I would use that personally. wxWidgets has AUI on the rewrite list also, but I wouldn't bet on any specific date, since that is the way open source rolls sometimes.

[auinotebooksample.zip](https://github.com/EmbroidePy/EmbroidePy/files/2322535/auinotebooksample.zip)

agw aui demo is here. It has many options tho... https://github.com/wxWidgets/Phoenix/blob/master/demo/agw/AUI.py

Also looked a bit closer at your code and see it wouldn't be too hard to rip most app stuff out of your view class and maybe make a official widget, so users needing a zoom view don't always have to ask on the mailing lists. The problem is that usually when you see a zoomer panel like this, it is so far integrated with the app no one wants to rip it out, or spends the time to make a proper control class one. the timeline project has a nice widget, but it is one of those things that is deeply integrated with the app, let alone the devs wouldnt spend time to rip it out lol. When wxPy gets to 4.1 here soon it will be a dev cycle relz so, I guess if ya want to help whip one up and get it in my MCOW package, it will be reviewed when Robin gets time. There are some other widgets I'd like to do also from other users but it usually boils down to time testing and making sample apps for the official demo. Plus I'm not really looking forward to the demo rewrite, since I ported it all to phoenix, but it has to happen eventually.

**Comment by tatarize** [comment]
wx.lib.agw.aui actually looks great. I would have used that previously if I knew it existed. Seems like a pretty solid attachment and relocation windowing system. And the code natively fixes fast close stuff. It by default works like I expect things to work. I have no strong attachment to the idea of using a notebook, I just wanted to do many panels and my gui builder wxGlade had that as a thing. 

The aui sample thing had some nice used wx.lib.embeddedimage stuff (though I couldn't get the demo (AUI.py) to run). I didn't know about the embeddedimage either. I didn't really add many tools because I didn't really want all the extra issues of including icon files, didn't even bother with a play button. Some embedded ones would make things rather awesome.

---

I've done some rather nice zooming and panning stuff, but in those cases the dc could just be fed a matrix. Like Android has it built in that you can pretty easily append a matrix.  The documentation didn't sound wildly hopeful that it was possible on all devices. Though "On some platforms (currently under MSW, GTK+ 3, OS X) wxDC has support for applying an arbitrary affine transformation matrix to its coordinate system" which might be preferred. I actually just fed it into:

```
        dc.SetLogicalOrigin(-self.matrix[MATRIX_TRANS_X], -self.matrix[MATRIX_TRANS_Y])
        dc.SetLogicalScale(self.matrix[MATRIX_SCALE_X], self.matrix[MATRIX_SCALE_Y])
```

But, that might have been an overcorrection. I also rolled up my own matrix, as the math isn't very hard for me.  But, I could just use wx.AffineMatrix2D and assume I'm in MSW, GTK+3, or OSX.

But, since you mention it, I could certainly see some clear utility in coding up a standalone ScenePanel like that.  I wrote an entire widget system for my Android app. So making a panel like that seemed pretty obvious. Though I could see why it might flummox people.  I could certainly take the current panel rip out all the app stuff and then just subclass that ScenePanel within my app. 

The android app version though is concerned with hitting elements within the scene, delegating the events afterwards to the  widget that was hit (simplifies things in a complex scene by a lot), translating the events into the scene space, drawing everything, switching out the entire widget tree, displaying on screen in scene toast messaging, dealing with the invalidation regions, multiple-concurrent animation, and some viewport functionality.

For a basic zoomer panel, I'd think it would just be translating points back and forth into the two different spaces, drawing in the two different spaces, basic info on the position of the viewport, helper functions for zoom on wheel scroll and wheel-click-and-drag pan, and some basic but often confusing functions like set viewport to look at this include this rectangle or ensure it views this particular point. Basically what I currently have, written in a bit more wx object using way, and with a couple helper functions you wouldn't often think about. Like when the view is rotated at an angle to know the position of the lower-left corner or some such things. It's not overly complex there, it's all just using that matrix but sometimes assumptions stop being true and you need helper functions.

**Comment by Metallicow** [comment]
As far as basic widgets go, if so and so operating system has a notebook and you can middle click close it, and there is a wxWidgets port, then it should work with a basic notebook. Certain widgets don't exist on other/all platforms, so oftentimes it will default to a generic version. Whatever the native widget acts like is the goal with the standard base ones. You can use dc to draw tabs, buttons, etc and stuff that look native also... often times this is where extra functionality is added. In generic versions or mixins. Ex: XP never had a grab the Frame bar fancyness of KDE where the whole frame goes half transparent when moving or grabbing it so you can see under it. I had to code it myself(even 7 snapping for that matter) .

Usually the demos can be run individually, but the snapshots, docs, demo builds are here https://wxpython.org/Phoenix/snapshot-builds/
EmbeddedImages should always work, but if you are missing loose file that may cause a failure also. The main demo houses all the smaller individual widget demos and a lot of them depend on sample files a lot of times. So if you want to check it out the correct way other than a file on github, download the whole demo Ex: wxPython-demo-4.0.4a1.dev3929+55c51b25.tar.gz extract and start it up with demo.py

Personally for my bigger projects as far as images go, I have 3 folders of stuff(__Images, _Images, Images) first one holds the development files(ex: psd, kra, etc), second holds the actual image(usually png), third one is a copy of the second one but optimized with a script that outputs all images as a importable file which never fails. The issue with pyembedded image is the fact you have to rebuild the whole file everytime there is a change in icon or whatever, but you dont have the hassle of missing file errors.
Smaller projects with a few files I always use loose stuff. Sample demos in source files I usually embed tho a small optimized image.

Ill update my fork latter and play around with the zoomer panel and see what I can do. Thanks.
