### ISSUE TITLE
Random Coloring With file.

### ISSUE THREAD

**Issue by Metallicow** [EmbroidePy/EmbroidePy#16]
I took Embroidermodder.PES and Star.DSB and loaded them into new agw aui notebook tabs. Then split the view and started playing with the star file points. The 2 colors are going random. Obviously a file cant really have a random color changing thread, unless it is optical fiber and has a color changing led running thru it haha.
Just want to bring this to attention.

**Comment by tatarize** [comment]
I know it exists, and I've considered fixing it. But, I haven't gotten around to a solution I like yet. Part of the reason is that it's not quite a bug. It's actually accurate. Data Stitch Barudan files contain needle assignments but they don't actually have any color information or thread information. When colors aren't assigned it picks a random one. Each time it is asked to refresh it picks new random colors. Hence the disco effect.

It isn't actually some discrete optical fiber with color changing LED it's actually an unmoored thread that could technically be anything. The file itself did not actually declare a color, and in part, claiming it has one is a lie. I could call embpattern.fix_color_count() and it make those colors discrete. It would find the number of color changes and assign the needed amount of random threads. 

But, I didn't really want to because it's, in theory, a lossy operation. You lose the fact that the loaded format didn't have any colors. It could have been that you loaded the data from a source with colors called random colors, or it could be you loaded from a source that had no colors. If you fill in the blanks you won't know.

Obviously I can't have it flickering up a storm like that. But, just because and RNG picked green, doesn't mean the actual file said that thread was actually green, in fact it gave no indication what color it was which seemed weirdly well reflected by that "unexpected feature". I was hoping to add a sort of basic color selector, or in some way have the user moor that color to something. 

There's also a weird oddness to when I get around to properly reflecting needle assignments I could have it go from needle 1 to needle 2 to needle 1 again, in a Barudan file without actually having colors. And this means I need a method that allows me to indicate that the second needle/color change goes back to the first color again, without ever having had a color assigned to that needle. Also while accounting for the very real happening of having enough colors that it cycles back through the needles without any expectation that the same needle still has the same color.

That or just have a palette of colors that I use in order when the color is not otherwise indicated.
